import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  section: {
    marginTop: 135,
    alignItems: "center",
  },
  container: {
    paddingVertical: 45,
    paddingHorizontal: 10,
    backgroundColor: "#AB7CE9",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: -4,
    },
    shadowOpacity: 0.15,
    shadowRadius: 5,
    elevation: 5,
    zIndex: 2,
    position: "relative",
    borderRadius: 30,
    width: 400,
    alignItems: "center",
  },
  title: {
    fontFamily: "Hagrid-Trial-Extrabold",
    fontSize: 32,
    letterSpacing: -0.3,
    color: "#fff",
    textAlign: "center",
    marginBottom: 29,
    width: 340,
  },
  firstText: {
    fontFamily: "Hagrid-Trial-Medium",
    fontSize: 16,
    letterSpacing: -0.15,
    lineHeight: 20,
    color: "#fff",
    textAlign: "center",
    marginBottom: 17,
  },
  text: {
    fontFamily: "Hagrid-Trial-Medium",
    fontSize: 16,
    letterSpacing: -0.15,
    lineHeight: 20,
    color: "#fff",
    textAlign: "center",
    marginBottom: 22,
    width: 340,
  },
  styledLink: {
    marginLeft: "auto",
    marginRight: "auto",
    alignItems: "center",
    justifyContent: "center",
    width: 197,
    height: 43,
    borderRadius: 54,
    borderWidth: 1,
    borderColor: "#fff",
    backgroundColor: "transparent",
  },
  linkText: {
    fontFamily: "eUkraine-Bold",
    letterSpacing: -0.2,
    textTransform: "uppercase",
    fontSize: 11,
    color: "#fff",
  },
  image: {
    position: "absolute",
    width: 131,
    height: 140,
    top: -76,
    right: 153,
    zIndex: 0,
  },
});
