import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  section: {
    paddingBottom: 65,
  },
  container: {
    padding: 10,
    alignItems: "center",
  },
  title: {
    marginBottom: 45,
    fontFamily: "Hagrid-Trial-Extrabold",
    fontSize: 32,
    letterSpacing: -0.2,
    color: "#fff",
    textAlign: "center",
    width: 300,
  },
  text: {
    fontFamily: "eUkraine-Medium",
    fontSize: 16,
    lineHeight: 20,
    letterSpacing: -0.45,
    color: "#fff",
    textAlign: "center",
    marginBottom: 23,
  },
  leftText: {
    fontFamily: "eUkraine-Medium",
    fontSize: 16,
    lineHeight: 20,
    letterSpacing: -0.45,
    color: "#fff",
    textAlign: "center",
    marginBottom: 23,
    marginBottom: 27,
  },
  leftBox: {
    fontFamily: "eUkraine-Medium",
    fontSize: 16,
    lineHeight: 20,
    letterSpacing: -0.45,
    color: "#fff",
    textAlign: "center",
    marginBottom: 23,
    marginBottom: 246,
    width: 300,
  },
  rightBox: {
    fontFamily: "eUkraine-Medium",
    fontSize: 16,
    lineHeight: 20,
    letterSpacing: -0.45,
    color: "#fff",
    textAlign: "center",
    marginBottom: 23,
    width: 300,
  },
  styledLink: {
    width: 252,
    height: 53,
    borderRadius: 59,
    backgroundColor: "#FE3FA0",
    alignItems: "center",
    justifyContent: "center",
    lineHeight: 53,
    marginTop: 10,
    alignSelf: "center",
  },
  styledLinkText: {
    textTransform: "uppercase",
    color: "#fff",
    fontFamily: "Hagrid-Trial-Heavy",
    fontSize: 11,
    letterSpacing: -0.3,
  },
  image: {
    position: "absolute",
    top: 343,
    right: -84,
    width: 414,
    height: 146,
  },
});
