import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  section: {
    paddingTop: 62,
    paddingBottom: 515,
    backgroundColor: "#fff",
    borderRadius: 33,
    overflowX: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -3 },
    shadowOpacity: 0.15,
    shadowRadius: 63,
  },
  container: {
    alignItems: "center",
    position: "relative",
  },
  title: {
    marginBottom: 45,
    fontSize: 32,
    fontFamily: "Hagrid-Trial-Extrabold",
    color: "#250C46",
    textAlign: "center",
    letterSpacing: "-0.3",
    width: 340,
  },
  text: {
    fontFamily: "Hagrid-Text-Trial-Medium",
    fontSize: 16,
    color: "#250C46",
    marginBottom: 15,
    textAlign: "center",
    width: 320,
  },
  lastText: {
    fontFamily: "Hagrid-Text-Trial-Medium",
    fontSize: 16,
    color: "#250C46",
    marginBottom: 15,
    textAlign: "center",
    marginBottom: 52,
    width: 320,
  },
  button: {
    backgroundColor: "#FE3FA0",
    borderRadius: 37,
    width: 231,
    height: 52,
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "center",
    marginBottom: 20,
  },
  buttonText: {
    fontSize: 14,
    fontFamily: "Hagrid-Trial-Heavy",
    color: "#fff",
    textTransform: "uppercase",
  },
  image: {
    width: 460,
    height: 420,
    position: "absolute",
    bottom: -470,
    left: -100,
    transform: [{ scaleX: -1 }],
  },
});
